### ISSUE TITLE
New default MessageOnlineUsersOnly does not work

### ISSUE THREAD

**Issue by MaretaDagostino** [ft-/arribasim-dev#75]
Commit bcb44f2 has implemented MessageOnlineUsersOnly = true as default because, if that value is set to false, group messages don't work at all. In the actual commit 378266f I tested group IMs, and it is impossible to send IMs. Actually the only known fix for this bug is setting MessageOnlineUsersOnly = true in OpenSim.ini or GridCommon.ini.

**Comment by shyrobbiani** [comment]
Möglicherweise wird der Wert durch OpenSim.Region.OptionalModules.Avatar.XmlRpcGroups.GroupsMessagingModule überschrieben.

**Comment by ft-** [comment]
setting this parameter to true disables all HG IMs for groups. There is no means for simulators to detect the online status of HG visitors. There is no overwriting. The modules independently extract data from the config. The whole group stuff is a mess.
